
import React, { useState } from 'react';
import type { ChatMessage } from '../types';
import { CopyIcon, CheckIcon } from './Icons';

interface MessageProps {
  message: ChatMessage;
}

// Simple markdown parser for **bold** text.
const renderText = (text: string) => {
    // Splits the string by the bold markdown, capturing the content in between.
    const parts = text.split(/\*\*(.*?)\*\*/g);
    return parts.map((part, i) => {
        // Every second part (odd index) is the one that was inside the asterisks.
        if (i % 2 === 1) {
            return (
                <strong 
                    key={i} 
                    className="text-transparent bg-clip-text bg-gradient-to-r from-emerald-400 to-cyan-400 font-bold"
                >
                    {part}
                </strong>
            );
        }
        return part;
    });
};

const Message: React.FC<MessageProps> = ({ message }) => {
  const [isCopied, setIsCopied] = useState(false);
  const isBot = message.sender === 'bot';
  const isInitialGreeting = message.id.startsWith('bot-initial-');

  const botStyles = 'bg-slate-700 text-slate-100 self-start';
  const userStyles = 'bg-emerald-600 text-white self-end';

  const handleCopy = () => {
    if (message.text) {
      navigator.clipboard.writeText(message.text);
      setIsCopied(true);
      setTimeout(() => setIsCopied(false), 2000);
    }
  };


  return (
    <div className={`group flex items-start gap-3 my-2 ${isBot ? 'flex-row' : 'flex-row-reverse'}`}>
      {isBot && (
        <div className="flex-shrink-0 w-8 h-8 flex items-center justify-center text-2xl">
          <span role="img" aria-label="Recycle Emoji">♻️</span>
        </div>
      )}
      <div
        className={`relative max-w-md md:max-w-lg rounded-xl px-4 py-3 whitespace-pre-wrap animate-fade-in-up ${
          isBot ? botStyles : userStyles
        }`}
      >
        {message.text && <p>{renderText(message.text)}</p>}
        {message.imageUrl && (
            <div className="mt-2 rounded-lg overflow-hidden bg-slate-800">
                <img 
                    src={message.imageUrl} 
                    alt="Generated by BebaBot" 
                    className="w-full h-auto object-cover" 
                    aria-label={`Generated image for prompt: ${message.text}`}
                />
            </div>
        )}
         {isBot && message.text && !isInitialGreeting && (
            <button
                onClick={handleCopy}
                aria-label={isCopied ? "Copied" : "Copy message"}
                className="absolute -top-2 -right-2 p-1.5 rounded-full bg-slate-600 text-slate-300 opacity-0 group-hover:opacity-100 transition-opacity duration-200 hover:bg-emerald-600 focus:opacity-100 focus:outline-none"
            >
                {isCopied ? <CheckIcon className="w-4 h-4 text-emerald-400" /> : <CopyIcon className="w-4 h-4" />}
            </button>
        )}
      </div>
    </div>
  );
};

export default Message;
